version: "3.4"

networks:
  backend:
  frontend:

x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100m

services:
  picspy-api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - backend
      - frontend
    env_file: 
      - .env
      
    environment: 
      MINIO_ACCESS_KEY: ${MINIO_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET}
      USESSL: ${USESSL}
      LIBS_DIR: /usr/src/app/libs
    ports:
      - "${API_EXTERNAL_PORT}:${API_INTERNAL_PORT}"
    volumes:
      - ./src:/usr/src/app/src
      - ./libs:/usr/src/app/libs
      - ./conf:/usr/src/app/conf
    depends_on: 
      - picspy-mongo
    networks: 
      - backend
      - frontend


  picspy-mongo:
    restart: always
    image: mongo:4.2.0
    volumes:
      - data:/data/db
    ports: 
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks: 
      - backend
      - frontend
    env_file: 
      - .env

volumes:
  postgres-data:
  redis-data:
  data:
  picspy_minio: